service: dni-ebased

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  ValidationHandler:
    handler: src/validation/handler/validationHandler.handler
    environment:
      QUEUE_URL: !Ref DNIQueue
    iamRoleStatementsName: ${self:service}-${self:provider.stage}-ValidationHandler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource:
          - !GetAtt DNIQueue.Arn
    events:
      - http:
          path: dni-ebased-sns/create
          method: post
          cors: true

  TransactionHandler:
    handler: src/transaction/handler/transactionHandler.handler
    environment: 
      TRANSACTION_TOPIC: !Ref DNITopic
      TABLE_NAME: !Ref DNITable
    iamRoleStatementsName: ${self:service}-${self:provider.stage}-TransactionHandler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:ReceiveMessage
        Resource:
          - !GetAtt DNIQueue.Arn
      - Effect: Allow
        Action:
          - sns:Publish
        Resource:
          - !Ref DNITopic
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - !GetAtt DNITable.Arn
    events:
      - sqs:
          arn:
            !GetAtt DNIQueue.Arn  

resources:
  Resources:
    DNIQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-DNIQueue
    DNITopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: DNI SNS Topic
        TopicName: ${self:service}-${self:provider.stage}-DNITopic
        Subscription:
          - Protocol: email
            Endpoint: marcosalejandrovalle@gmail.com
    DNITable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-DNITable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE